
#
# Copyright 2019 Bull S.A.S. Atos Technologies - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Install python requirements
  hosts: all
  become: true
  vars:
    pip_extra_args: ""
  tasks:
  - name: Install pip
    easy_install:
      name: pip
      state: latest  

  - name: Install 'virtualenv' package
    pip:
      name: virtualenv
      state: latest
  
  - name: Set virtualenv path
    set_fact:
      VIRTUAL_ENV_PATH: "/usr/local/py-env-{{NODE}}"

  - name: Force installation of at least one package
    set_fact:
      PACKAGES: ["pip"]
    when: PACKAGES  | length == 0

  - name: Set alternate pip index url
    set_fact:
      pip_extra_args: "-i {{PIP_INDEX_URL}}"
    when: PIP_INDEX_URL is defined and PIP_INDEX_URL  | length > 0

  - name: Dumping packages to install
    debug: 
      var: PACKAGES

  - name: Install python packages
    pip:
      name: "{{PACKAGES}}"
      extra_args: "{{pip_extra_args}}"
      virtualenv: "{{ VIRTUAL_ENV_PATH }}"
      virtualenv_python: "python{{VERSION}}"
