#
# Ystia Forge
# Copyright (C) 2018 Bull S. A. S. - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.
#
- name: Install ansible docker_image requirements
  hosts: all
  become: true
  tasks:
  - name: check if pip is installed
    command: "pip --version"
    ignore_errors: true
    changed_when: false
    check_mode: no
    register: pip_found
  # No need to go further if pip is already installed
  - meta: end_play
    when: pip_found.rc == 0

  - name: Get python version
    python_requirements_info:
    register: pyinfo
    failed_when: "pyinfo == None or pyinfo.python_version == None or pyinfo.python_version == ''"
  - name: Download pip
    get_url:
      url: https://bootstrap.pypa.io/get-pip.py
      dest: /tmp/get-pip.py
  - name: Install pip
    command: "{{ pyinfo.python }} /tmp/get-pip.py"
  - name: cleanup downloaded file
    file:
      state: absent
      path: /tmp/get-pip.py
  - name: Install 'docker' python package
    pip:
      name: docker
