#
# Ystia Forge
# Copyright (C) 2020 Bull S. A. S. - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.
#
- name: Load Docker image from tar archive
  hosts: all
  tasks:
  - name: Get archive PATH defined at runtime
    set_fact:
      archive_path: "{{RUNTIME_PATH}}"
    when: RUNTIME_PATH != ""
  - name: Get archive PATH property
    set_fact:
      archive_path: "{{PATH}}"
    when: RUNTIME_PATH == ""
    failed_when: RUNTIME_PATH == "" and PATH == ""
  - name: Get user defined at runtime
    set_fact:
      user_loading: "{{RUNTIME_USER}}"
    when: RUNTIME_USER != ""
  - name: Get user property
    set_fact:
      user_loading: "{{USER}}"
    when: RUNTIME_USER == ""
    failed_when: RUNTIME_USER == "" and USER == ""
  - name: Load tar archive
    docker_image:
      name: "{{NAME}}"
      tag: "{{TAG}}"
      push: "{{PUSH}}"
      repository: "{{REPOSITORY}}"
      load_path: "{{archive_path}}"
      source: load
      force_source: "{{FORCE_LOAD}}"
    become: true
    become_user: "{{user_loading}}"
    become_method: sudo
    register: result
  - name: Fail if the image specified does not correpond to the archive specified
    debug:
      msg: "Checking if image {{NAME}} {{TAG}} is in tar archive {{PATH}}"
    failed_when: result.image == None
  - name: Check if an image was loaded
    debug:
      msg: "Image {{NAME}} {{TAG}} already loaded"
    when: result.image == {}
  - name: Intialize fact used in opration output
    set_fact:
      REPO_TAGS: []
  - name: Set repo tags output if returned by docker_image
    set_fact:
      REPO_TAGS: "{{result.image.RepoTags | to_json}}"
    when: result.image != None and result.image != {}
