- name: Unseal Vault by API calls
  hosts: all
  strategy: free
  become: true
  tasks:
    - name: Init Vault over HTTPS
      uri:
        url: "https://{{ VAULT_IP }}:{{ VAULT_PORT }}/v1/sys/init"
        method: PUT
        body_format: json
        body: 
          secret_shares: "{{ KEY_SHARE }}"
          secret_threshold: "{{ KEY_THRESHOLD }}"
        client_cert: "{{ CONFIG_DIR }}/vault.pem"
        client_key: "{{ CONFIG_DIR }}/vault.key"
        validate_certs: no
      register: resp
      when: not (VAULT_TLS_DISABLED | bool)

    - name: Init Vault over HTTP
      uri:
        url: "http://{{ VAULT_IP }}:{{ VAULT_PORT }}/v1/sys/init"
        method: PUT
        body_format: json
        body:
          secret_shares: "{{ KEY_SHARE }}"
          secret_threshold: "{{ KEY_THRESHOLD }}"
      register: resp
      when: VAULT_TLS_DISABLED | bool

    - name: Unseal Vault over HTTPS
      uri:
        url: "https://{{ VAULT_IP }}:{{ VAULT_PORT }}/v1/sys/unseal"
        method: PUT
        body_format: json
        body:
          key: "{{ item }}"
        client_cert: "{{ CONFIG_DIR }}/vault.pem"
        client_key: "{{ CONFIG_DIR }}/vault.key"
        validate_certs: no
      when: not (VAULT_TLS_DISABLED | bool) and index < KEY_THRESHOLD
      loop: "{{ resp.json['keys'] }}"
      loop_control:
        index_var: index

    - name: Unseal Vault over HTTP
      uri:
        url: "http://{{ VAULT_IP }}:{{ VAULT_PORT }}/v1/sys/unseal"
        method: PUT
        body_format: json
        body:
          key: "{{ item }}"
      when: VAULT_TLS_DISABLED | bool and index < KEY_THRESHOLD
      loop: "{{ resp.json['keys'] }}"
      loop_control:
        index_var: index
