- name: Unseal Vault by API calls
  hosts: all
  strategy: free
  become: true
  tasks:
    - name: Set API url HTTPS
      set_fact:
        vault_api_url: "https://{{ VAULT_IP }}:{{ VAULT_PORT }}"
      when: not (VAULT_TLS_DISABLED | bool)
    - name: Set API url HTTP
      set_fact:
        vault_api_url: "http://{{ VAULT_IP }}:{{ VAULT_PORT }}"
      when: VAULT_TLS_DISABLED | bool

    - name: Init Vault
      uri:
        url: "{{ vault_api_url }}/v1/sys/init"
        method: PUT
        body_format: json
        body: >
          {
            "secret_shares": {{ KEY_SHARE | int }},
            "secret_threshold": {{ KEY_THRESHOLD | int }}
          }
        client_cert: "{{ CONFIG_DIR }}/vault.pem"
        client_key: "{{ CONFIG_DIR }}/vault.key"
        validate_certs: no
      register: resp

    - name: Register attributes
      set_fact:
        ROOT_TOKEN: "{{ resp.json.root_token }}"
        UNSEAL_KEYS: "{{ resp.json['keys'] | join(' ; ') }}"

    - name: Unseal Vault
      uri:
        url: "{{ vault_api_url }}/v1/sys/unseal"
        method: PUT
        body_format: json
        body:
          key: "{{ item }}"
        client_cert: "{{ CONFIG_DIR }}/vault.pem"
        client_key: "{{ CONFIG_DIR }}/vault.key"
        validate_certs: no
      when: index < (KEY_THRESHOLD | int)
      loop: "{{ resp.json['keys'] }}"
      loop_control:
        index_var: index
